# Alembic migration script template
# See Alembic documentation for instructions at:
# https://alembic.sqlalchemy.org/

"""Add carbon measurement support

Revision ID: 5abe8f5d168a
Revises: 74eb13dacb6b
Create Date: 2026-02-11 13:45:11.560193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abe8f5d168a'
down_revision = '74eb13dacb6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_farms_created_at'), 'farms', ['created_at'], unique=False)
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_created_at'), 'measurements', ['created_at'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_created_at'), table_name='measurements')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_created_at'), table_name='farms')
    # ### end Alembic commands ###
