# Alembic migration script template
# See Alembic documentation for instructions at:
# https://alembic.sqlalchemy.org/

"""Add Farm and Measurement models for Phase 4

Revision ID: 74eb13dacb6b
Revises: ae3b60024a7b
Create Date: 2026-02-11 13:28:03.927736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74eb13dacb6b'
down_revision = 'ae3b60024a7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_company_id'), 'farms', ['company_id'], unique=False)
    op.create_index(op.f('ix_farms_is_active'), 'farms', ['is_active'], unique=False)
    op.create_index(op.f('ix_farms_name'), 'farms', ['name'], unique=False)
    op.create_table('measurements',
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'measurement_type', 'measurement_date', name='uq_farm_measurement_date')
    )
    op.create_index(op.f('ix_measurements_farm_id'), 'measurements', ['farm_id'], unique=False)
    op.create_index(op.f('ix_measurements_measurement_date'), 'measurements', ['measurement_date'], unique=False)
    op.create_index(op.f('ix_measurements_measurement_type'), 'measurements', ['measurement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_measurement_type'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_measurement_date'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_farm_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_farms_name'), table_name='farms')
    op.drop_index(op.f('ix_farms_is_active'), table_name='farms')
    op.drop_index(op.f('ix_farms_company_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
