"""Add satellite status model

Revision ID: a1b2c3d4e5f6
Revises: 8a9c1d2e3f4a
Create Date: 2026-02-11 10:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '8a9c1d2e3f4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_status',
    sa.Column('satellite_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('coverage_percent', sa.Float(), nullable=False),
    sa.Column('accuracy_percent', sa.Float(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('uptime_percent', sa.Float(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('health_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_name')
    )
    op.create_index(op.f('ix_satellite_status_created_at'), 'satellite_status', ['created_at'], unique=False)
    op.create_index(op.f('ix_satellite_status_id'), 'satellite_status', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_status_satellite_name'), 'satellite_status', ['satellite_name'], unique=False)
    op.create_index(op.f('ix_satellite_status_status'), 'satellite_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satellite_status_status'), table_name='satellite_status')
    op.drop_index(op.f('ix_satellite_status_satellite_name'), table_name='satellite_status')
    op.drop_index(op.f('ix_satellite_status_id'), table_name='satellite_status')
    op.drop_index(op.f('ix_satellite_status_created_at'), table_name='satellite_status')
    op.drop_table('satellite_status')
    # ### end Alembic commands ###
